server {
  listen 8080;
  listen 8443 ssl;
  server_tokens on;
  ssl_certificate /etc/nginx/tls/lab.crt;
  ssl_certificate_key /etc/nginx/tls/lab.key;
  ssl_protocols TLSv1.2 TLSv1.3;

  location /api/ {
    proxy_pass http://api:8000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location / { proxy_pass http://app/; }
}
